# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Caleb Washburn
tagline:          'Personal Portfolio'
description:      'Software Engineering, C++ design patterns, embedded firmware, hardware design, serial project starter'
url:              http://github.com/hyperbolic-labs/
baseurl:          ""

author:
  name:           'Caleb Washburn'
  # url:            https://twitter.com/mdo

paginate:         1

mathjax: true

# Custom vars
version:          2.1.0

github:           http://github.com/hyperbolic-labs/
  repo:           https://github.com/hyperbolic-labs/telesonde

plugins:
  - jekyll-gist
  - jekyll-paginate
